name: serentipia_gpu
channels:
  - pyg
  - defaults
dependencies:
  - python=3.10
  - seaborn
  - pandas
  - catboost
  - lightgbm
  - matplotlib
  - scikit-learn==1.7.1
  - tqdm
  - joblib
  - optuna
  - numpy
  - ninja
  - cython
  - ipykernel
  - imbalanced-learn==0.12.4
  - libstdcxx-ng
  - libgcc-ng
  - gcc_linux-64=13.1.0
  - gxx_linux-64=13.1.0
  - boost
  - boost-cpp
  - shap
  - nilearn
  - umap-learn
  - xgboost
  - scikit-image
  - typer
  - pytorch-cuda=11.8
  - torchvision=0.18.0
  - pytorch=2.3.0
  - torchaudio=2.3.0
  - protobuf
  - tabulate
prefix: /home/diego/anaconda3/envs/serentipia_gpu
